# Condition

In [1]:
money=2000
if (money>1000) & (money>1999):
    print("true")

true


# Loop

In [2]:
i=0
n=10
while i<n:
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9


In [ ]:
i=int(input())

In [ ]:
i

In [12]:
import numpy 

In [13]:
numpy.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
numpy.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
a=[4,4,3,3]
a[0]

4

In [18]:
type(a)

list

In [20]:
population=np.random.rand(30)

In [21]:
population

array([0.04882702, 0.67495696, 0.13303344, 0.87692462, 0.63762436,
       0.86796718, 0.12165028, 0.615041  , 0.26242786, 0.01525779,
       0.17396317, 0.7347972 , 0.95299815, 0.77505527, 0.59525011,
       0.57186993, 0.52035534, 0.83206507, 0.44355784, 0.84630667,
       0.08861829, 0.99760471, 0.29926102, 0.01658016, 0.14940951,
       0.24031733, 0.95712588, 0.78021281, 0.25610664, 0.5815006 ])

In [22]:
sample=np.random.choice(population,15)

In [23]:
sample

array([0.95712588, 0.25610664, 0.83206507, 0.01525779, 0.29926102,
       0.7347972 , 0.5815006 , 0.01525779, 0.84630667, 0.01658016,
       0.14940951, 0.67495696, 0.95299815, 0.5815006 , 0.14940951])

In [ ]:
a=int(input("enter a value"))

In [ ]:
a

In [ ]:
for i in range(1,10):
    print(i)

In [ ]:
#loof
